### ISSUE TITLE
Missing vendor and host consent before OneTrustLoaded

### ISSUE THREAD

**Issue by MTrykar** [taneli-salonen1/gtm-onetrust-consent-groups#1]
Hello Taneli,

I am testing your variable template on a website where I also use vendor/host level consent from OneTrust. Unfortunately, I cannot see the vendor and host consent before OneTrust is loaded.

![image](https://user-images.githubusercontent.com/7345489/162961865-07faa9b4-765d-4e6c-be28-135208d189b9.png)

When the OneTrustLoaded event is called I see the full consent in the variable:

![image](https://user-images.githubusercontent.com/7345489/162961806-30390ad5-2b65-46e5-8fba-e2208d08fb3a.png)

The OptanonConsent cookie contains this information once it is set (groups=C0001:1,C0002:1&hosts=H24:1&genVendors=V1:1,). Is there a way to read all three "parameters" from the cookie?

Best regards,
Manuel

**Comment by taneli-salonen1** [comment]
Hi Manuel,

I never came across vendor and host level consent in OneTrust before. I modified the template slightly to include those values from the cookie as well. Thanks for pointing that out.

Taneli
