### ISSUE TITLE
i dont see the template in the community gallery? when searching in gtm

### ISSUE THREAD

**Issue by simonmadsen** [taneli-salonen1/gtm-onetrust-consent-groups#2]

**Comment by taneli-salonen1** [comment]
![image](https://user-images.githubusercontent.com/23078093/169642061-962278cd-223b-4fdc-9ea6-b25f110566b5.png)

Hi! It seems to be in the gallery now at least.

**Comment by simonmadsen** [comment]
Yeah sorry forgot to update this.
A week agi it was there.
Then disappeared a day later but then cam back a day after.

Btw cant you help tlswade improve the gtm tag template for onetrust?
________________________________

**Comment by taneli-salonen1** [comment]
I hadn't even noticed that there's tag template for OneTrust. I'll need to take a look into it. 

I would hope for OneTrust themselves to realize that after all the new datalayer messages they've added over the years, their GTM integration is still a mess. Would be nice if they provided a proper template for consent mode.

**Comment by simonmadsen** [comment]
Well you know the one that is made is good, i just Wonder Why dev does not publish the fork pull i made

So can you pull it all together or talk with swade or What his name for everly or so ?

Fra: Taneli ***@***.***>
Sendt: 21. maj 2022 13:45
Til: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Emne: Re: [taneli-salonen1/gtm-onetrust-consent-groups] i dont see the template in the community gallery? when searching in gtm (Issue #2)


I hadn't even noticed that there's tag template for OneTrust. I'll need to take a look into it.

I would hope for OneTrust themselves to realize that after all the new datalayer messages they've added over the years, their GTM integration is still a mess. Would be nice if they provided a proper template for consent mode.
